<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Adobe\AxpConnector\Block\Cart $block
 * @var \Adobe\AxpConnector\ViewModel\Js $viewModel
 */
$viewModel = $block->getViewModel();
$datalayerName = $block->escapeJs($viewModel->getDatalayerName());
?>
<script type="text/javascript" id="axpconnector-datalayer-cart-viewed">
    window.<?= /* @noEscape */ $datalayerName ?>.push(<?= /* @noEscape*/ $block->datalayerJson() ?>);
</script>
