<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Adobe\AxpConnector\Block\Js
 */
$datalayerName = $block->getDatalayerName();
?>
<script type="text/javascript">
    window.<?= /* @noEscape */ $datalayerName ?> = window.<?= /* @noEscape */ $datalayerName ?> || [];
</script>
<script src="<?= /* @noEscape */ $block->getScriptUrl(); ?>" async></script>
