<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Adobe\AxpConnector\ViewModel\Js $viewModel
 */
$viewModel = $block->getViewModel();
$datalayerName = $block->escapeJs($viewModel->getDatalayerName());
?>
<script type="text/javascript">
    window.<?= /* @noEscape */ $datalayerName ?> = window.<?= /* @noEscape */ $datalayerName ?> || [];
</script>
<script src="<?= /* @noEscape */ $block->escapeUrl($viewModel->getScriptUrl()); ?>" async></script>
