<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Adobe\AxpConnector\Block\Listing $block
 */
$dln = $block->datalayerName();
?>
<script type="text/javascript" id="axpconnector-datalayer-category-viewed">
    <?php $datalayerJson = $block->datalayerJson(); ?>
    <?php if ($datalayerJson) : ?>
        window.<?= /* @escapeNotVerified */ $dln ?>.push(<?= /* @escapeNotVerified */ $block->datalayerJson() ?>);
    <?php endif; ?>
</script>
