<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

$dln = $block->datalayerName();
?>
<?php if ($block->helper()->isEnabled()) : ?>
    <script type="text/javascript" id="axpconnector-datalayer-page-loaded">
        window.<?= /* @escapeNotVerified */ $dln ?> = window.<?= /* @escapeNotVerified */ $dln ?> || [];
        window.<?= /* @escapeNotVerified */ $dln ?>.push(<?= /* @escapeNotVerified */ $block->datalayerPageJson() ?>);
    </script>
<?php endif; ?>
