<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Framework\View\Element\AbstractBlock $block
 */
?>
<div data-role="launch" data-bind="scope: 'launch'">
    <div class="content-type" data-bind="html: launch().datalayerScript"></div>
</div>
<script type="text/x-magento-init">
{
  "[data-role=launch]": { "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout(); ?> }
}
</script>
