<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

$dln = $block->datalayerName();
?>
<script type="text/javascript" id="axpconnector-datalayer-search-results">
    window.<?= /* @escapeNotVerified */ $dln ?> = window.<?= /* @escapeNotVerified */ $dln ?> || [];

    <?php $datalayerJson = $block->datalayerJson(); ?>
    <?php if ($datalayerJson) : ?>
        window.<?= /* @escapeNotVerified */ $dln ?>.push(<?= /* @escapeNotVerified */ $datalayerJson ?>);
    <?php endif; ?>
</script>