<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script type="text/javascript" id="axpconnector-datalayer-search-results">
    window.AppEventData = window.AppEventData || [];
    <?php $datalayerJson = $block->datalayerJson(); ?>
    <?php if ($datalayerJson) : ?>
        window.AppEventData.push(<?= /* @escapeNotVerified */ $datalayerJson ?>);
    <?php endif; ?>
</script>