<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Adobe\AxpConnector\Block\Search $block
 * @var \Adobe\AxpConnector\ViewModel\Js $viewModel
 */
$viewModel = $block->getViewModel();
$datalayerName = $block->escapeJs($viewModel->getDatalayerName());
$datalayerJson = $block->datalayerJson();
?>
<script type="text/javascript" id="axpconnector-datalayer-search-results">
    <?php if ($datalayerJson) : ?>
        window.<?= /* @noEscape */ $datalayerName ?>.push(<?= /* @noEscape */ $datalayerJson ?>);
    <?php endif; ?>
</script>
