<?php
$_helper = $this->helper('SearchDiscovery\LaunchByAdobe\Helper\Data');
?>

<?php if ($_helper->isEnabled()) : ?>
  <script type="text/javascript" id="launchbyadobe-datalayer-container">
    // Datalayer goes here
    window.AppEventData = window.AppEventData || [];
    <?php foreach($block->encodedDatalayerEvents() as $eventJson) : ?>
      window.AppEventData.push(<?php echo $eventJson ?>);
    <?php endforeach; ?>
  </script>


  <script type="text/x-magento-init">
    {
        "*": {
            "launchbyadobe": {}
        }
    }
  </script>
<?php endif; ?>
