<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Adobe\Launch\ViewModel\Js $viewModel
 */
$viewModel = $block->getViewModel();
$datalayerName = $block->escapeJs($viewModel->getDatalayerName());
?>
<script type="text/x-magento-init">
{
    "*": {
        "Adobe_Launch/js/view/launch": {
            "datalayerName": "<?= /* @noEscape */ $datalayerName ?>"
        }
    }
}
</script>
